# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: golang打包

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'

    - name: Build
      run: go build  -o tmd .

#    - name: Upload Artifact (Linux)
#      uses: actions/upload-artifact@v4
#      with:
#        name: tmd
#        path: ./tmd
#        if-no-files-found: ignore
